// Code generated by "stringer -type FileProcMode"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APPEND-0]
	_ = x[CHMOD-1]
	_ = x[COPY-2]
	_ = x[SKIP-3]
}

const _FileProcMode_name = "APPENDCHMODCOPYSKIP"

var _FileProcMode_index = [...]uint8{0, 6, 11, 15, 19}

func (i FileProcMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FileProcMode_index)-1 {
		return "FileProcMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileProcMode_name[_FileProcMode_index[idx]:_FileProcMode_index[idx+1]]
}
