// Code generated by "stringer -type=FileProcMode"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Append-0]
	_ = x[Copy-1]
}

const _FileProcMode_name = "AppendCopy"

var _FileProcMode_index = [...]uint8{0, 6, 10}

func (i FileProcMode) String() string {
	if i < 0 || i >= FileProcMode(len(_FileProcMode_index)-1) {
		return "FileProcMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileProcMode_name[_FileProcMode_index[i]:_FileProcMode_index[i+1]]
}
